spring.application.name=credit_scoring


server.port=9095
spring.jpa.hibernate.ddl-auto=update
  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.main.allow-circular-references=true
security.ignored="*.bundle.*"

#dev
spring.datasource.url=jdbc:postgresql://localhost:5432/credit_scoring
spring.datasource.username=postgres
spring.datasource.password=postgres


#spring.datasource.url=${BD_LATROP_URL}/credit_scoring
#spring.datasource.username=${BD_LATROP_EMANRESU}
#spring.datasource.password=${BD_LATROP_DROWSSAP}




#mail.smtp.url=${PTMS_LRU}
#mail.smtp.password=${DROWSSAP_RESU_PTMS}
#mail.smtp.username=${EMANRESU_PTMS}





mail.smtp.url=${PTMS_LRU}
mail.smtp.username=${EMANRESU_PTMS}
mail.smtp.password=${DROWSSAP_RESU_PTMS}

t24.user.name=${T24_USER_NAME}
t24.user.password=${T24_USER_PASSWORD}
t24.cbs.url=${T24_CBS_ADDRESS}


jwt.secret= ${YEK_TERCES_TWJ}
jwt.expiration=30000000
application.security.jwt.refresh-token.expiration=6048000000000

notification.outlook.address=http://10.1.125.197:9081

#notification.sasv.address=http://10.1.125.58:8085
#notification.outlook.address=http://localhost:9081




spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=true



# OpenAPI / Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.doc-expansion=none
springdoc.show-actuator=false